### ISSUE TITLE
issue when importing into environment

### ISSUE THREAD

**Issue by Doml12** [AndrewButenko/ABControlsToolkit#18]
Hi, i get an issue when trying to deploy this into a sandbox environment in powerapps. below is the error message.

![image](https://github.com/AndrewButenko/ABControlsToolkit/assets/137183961/0b761b59-1735-4a8f-b3ae-8afea4a5ab17)

**Comment by AndrewButenko** [comment]
Hello,
Seems you imported the wrong file. Try to use this - https://github.com/AndrewButenko/ABControlsToolkit/releases/download/1.0.0.5/ABControlsToolkit_1_0_0_5_managed.zip
Closing the issue.
Andrew
